name: Restart / Update Prod SNS Uptime

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
  workflow_dispatch:

jobs:
  restart-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to Remote Server via SSH and Restart Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo su
            cd /home/uptime-kuma/
            docker compose pull
            docker compose up -d
            docker image prune -f
